# Generated by Django 3.1.3 on 2021-04-17 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='persons',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='id',
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(23)]),
        ),
    ]
